load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")



swift_library(
    name = "WGUI",
    module_name = "WGUI",
    srcs = glob([
        
    ]),
    deps = [
        "//submodules/AccountContext:AccountContext",
        "//submodules/Display:Display",
        "//submodules/ItemListUI:ItemListUI",
        "//submodules/Postbox:Postbox",
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit",
        "//submodules/TelegramCore:TelegramCore",
        "//submodules/TelegramNotices:TelegramNotices",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/TelegramUIPreferences:TelegramUIPreferences",
        "//submodules/PresentationDataUtils:PresentationDataUtils",
        "//submodules/PeersNearbyIconNode:PeersNearbyIconNode",
        "//submodules/TelegramPermissionsUI:TelegramPermissionsUI",
        "//submodules/UndoUI:UndoUI",
        "//submodules/ContextUI:ContextUI",
        "//Wellgram/WGData:WGData",
        "//Wellgram/WGStrings:WGStrings"
    ],
    visibility = [
        "//visibility:public",
    ],
)
