load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "WGWebUtils",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//Wellgram/WGData:WGData",
        "//submodules/Postbox:Postbox#shared",
        "//submodules/TelegramCore:TelegramCore#shared"
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
